<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>avatar_verify</AssemblyName>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MapleClient">
      <HintPath>F:\CODE\MapleGodot\maple-client\.godot\mono\temp\bin\Debug\MapleClient.dll</HintPath>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>F:\CODE\MapleGodot\maple-client\.godot\mono\temp\bin\Debug\GodotSharp.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
